# syntax version.
version: "3.7"

# services list.
services:
  # base image
  alpine-base:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-base"
    build:
      context: "${PHP_VERSION}/alpine/base"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}

  # swoole image
  alpine-cli:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-cli-v${SWOOLE_VERSION}"
    build:
      context: "${PHP_VERSION}/alpine/cli"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SWOOLE_VERSION: ${SWOOLE_VERSION}

  # swow image
  alpine-swow:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-swow-${SW_VERSION}"
    build:
      context: "${PHP_VERSION}/alpine/swow"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SW_VERSION: ${SW_VERSION}

  # dev image
  alpine-dev:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-dev"
    build:
      context: "${PHP_VERSION}/alpine/dev"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
