name: Build Swoole

on: [push]
env:
  ENGINE: "swoole"
  SW_VERSION: "v4.5.7"
  COMPOSER_VERSION: "2.0.6"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Build Alpine ${{ matrix.alpine-version }} on PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    env:
      ALPINE_VERSION: "${{ matrix.alpine-version }}"
      PHP_VERSION: "${{ matrix.php-version }}"
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        php-version: ['7.3', '7.4']
        alpine-version: ['3.9', '3.10', '3.11']
      max-parallel: 6
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: ./.github/workflows/build.sh
