name: Build Docker

on: [push, pull_request]

jobs:
  build-73-alpine-v309-swow:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 7.4
      ALPINE_VERSION: 3.11
      SW_VERSION: develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose build alpine-swow
      - name: Login
        run: docker login docker.pkg.github.com -u hyperf -p ${{ secrets.GITHUB_TOKEN }}
      - name: Tag
        run: docker tag hyperf/hyperf:$PHP_VERSION-alpine-$vALPINE_VERSION-swow-$SW_VERSION docker.pkg.github.com/hyperf/hyperf-docker/hyperf:$PHP_VERSION-alpine-$vALPINE_VERSION-swow-$SW_VERSION
      - name: Push
        run: docker push docker.pkg.github.com/hyperf/hyperf-docker/hyperf:$PHP_VERSION-alpine-$vALPINE_VERSION-swow-$SW_VERSION
