name: Buildx Base Image

on:
  workflow_dispatch:
    inputs:
      event:
        description: 'Input your event'
        required: true
        default: ''

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
  SW_VERSION: 4.6.4

jobs:
  build:
    name: Build Base Image
    runs-on: 'ubuntu-latest'
    env:
      PHP_VERSION: '${{ matrix.php-version }}'
      ALPINE_VERSION: '${{ matrix.alpine-version }}'
    strategy:
      matrix:
        php-version: [ '7.4' ]
        alpine-version: [ '3.13']
        exclude:
          - php-version: '7.4'
            alpine-version: '3.16'
      max-parallel: 12
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker buildx build -t hyperf/hyperf:${{ matrix.php-version }}-alpine-v${{ matrix.alpine-version }}-base --platform=linux/arm,linux/arm64,linux/amd64 -f ./7.4/alpine/base/Dockerfile
          docker buildx build -t hyperf/hyperf:${{ matrix.php-version }}-alpine-v${{ matrix.alpine-version }}-swoole-$SW_VERSION --platform=linux/arm,linux/arm64,linux/amd64 -f ./7.4/alpine/swoole/Dockerfile
      # - name: Push Images to Docker Hub
      #   if: ${{ github.event.inputs.event == 'publish' }}
      #   run: |
      #     docker login --username limingxinleo -p $DOCKERHUB_TOKEN
      #     docker push hyperf/hyperf:${{ matrix.php-version }}-alpine-v${{ matrix.alpine-version }}-base


